### PR TITLE
Added messages and delay on success/error of button

### PR DESCRIPTION
**Pull request by NewDark90**
Added handlers for onSuccess/onError
Added in examples
Added beginnings of definition file

New branch as I borked the last one I think. Fixes included.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you for your additions. They seem to work nicely! 
Three things:
1. What do we need the type script file for?
2. The example animation of the loading circle fading back when the loading is finished seems to be broken. Have a look at the current example http://johannesjo.github.io/angular-promise-buttons/ and compare it to the one you would have in your feature branch.
3. To make sure, all works as intended in the future, we also would need some unit tests for the new behavior.

**Comment by NewDark90** [comment]
No problem. I really like what you've done with it and I'm glad we can collaborate.

1. Technically nothing. It doesn't really do anything but give a description of the expected types. For those using the definition they get strong typing and auto completion. I was probably going to add it to DefinitelyTyped later/eventually, but have it here for now. 
2. I can check that out and see what I can do with it. So close. :)
3. I've literally never done that. I can look into it though, for sure.

**Comment by johannesjo** [comment]
@NewDark90 About 3: Maybe the existing unit test can guide you. If you have questions, don't hesitate to ask!

**Comment by johannesjo** [comment]
Hey. Thank you for reworking your PR. Could you maybe check why the code coverage decreased by that much?

Also: What's the use of the TypeScript file. Haven't seen that before.

**Comment by NewDark90** [comment]
@johannesjo I won't be doing that. I looked over the tests you had set up and noped out of there so fast. I've got the library working the way I need. I'm not writing an extra 3x the code to check it over. 

You don't have to accept the pull request, but you are more than welcome to cannibalize/ignore anything done here. 

As for the typescript file, it does nothing unless you are using Typescript. I can reference that file and suddenly I get static type checking and intellisense. Here's an example of some of the benefits that I get while using it. (Never mind the ES6 syntax sugar which is so so sweet :+1:)
image

**Comment by johannesjo** [comment]
@NewDark90 Thanks for your feedback and thanks for the work you've done. I'll look into it once I've more time, but I can't merge it as is.

**Comment by NewDark90** [comment]
@johannesjo Not a problem. Fully understand. :)

**Pull request merged**
