### PR TITLE
Added support to set directive priority and to compile HTML template.

### PR DESCRIPTION
**Pull request by mrbatista**

### CODE REVIEW

**Comment by mrbatista** [comment]
@johannesjo PTAL.
Thanks

**Comment by johannesjo** [comment]
Thank you very much for the pr.  I'll check it once I'm back from vacation.

**Comment by johannesjo** [comment]
Also you might want to rebase the upstream repo before pushing again. It seems like that some of the npm packages were not working anymore in their older versions, so I had to update them.

**Comment by mrbatista** [comment]
@johannesjo I need to set priority and $compile template because use angular-material directive `md-button`:
```html
<md-button class="md-primary" ng-click="yourServiceCaller()" 
           promise-btn>Primary Button</md-button>
```

**Comment by johannesjo** [comment]
The thing is, that -[according to the docs](https://docs.angularjs.org/api/ng/service/$compile) - the default priority should be already 0. 
To be honest, I also don't understand why $compiling the template fixes the issue with <md-button>. What is not working?

**Comment by mrbatista** [comment]
This PR introduce **possibility** to modify default priority.
My provider configuration is:
```javascript
angularPromiseButtonsProvider.extendConfig({
    spinnerTpl: '<span class="md-button-spinner"><md-progress-circular ' +
    'class="md-warn md-hue-2" md-mode="indeterminate" md-diameter="16">' +
    '</md-progress-circular></span>',
    btnLoadingClass: 'is-loading',
    priority: 1
  });
```

1. My spinner template is also a directive, without $compile does not work (see directive `md-progress-circular`).
2. `md-button` directive have transclude option set to `true` (https://github.com/angular/material/blob/master/src/components/button/button.js#L122) and as official angular documentation, priority to 0 (is not set and then default priority). If I don't change priority, `spinnerTpl` is not included.

**Comment by johannesjo** [comment]
Sorry. You're right. It's a little late maybe for checking code ;). I'll check again tomorrow. The PR  looks good! The only thing missing would be unit tests, to assure the new functionality is working. Thank you very much for your work!

**Comment by johannesjo** [comment]
I merge the PR for now. Thank you! It would be really cool though, if you could provide another PR with the missing unit tests.

**Comment by mrbatista** [comment]
@johannesjo This is [this](https://github.com/mrbatista/angular-promise-buttons/commit/a6b676672c4864255bfefc9dac947b8cc2f90592) commit with unit tests for priority.

**Comment by mrbatista** [comment]
@johannesjo for $compile support this is just a compile template... Do you need unit tests for this functionality too?

**Comment by johannesjo** [comment]
@mrbatista won't hurt but I think is it not necessary :) Thanks again for your work!

**Pull request merged**
